spring:
  security:
    user:
      name: buzz
      password: infinity
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
server:
  port: 8443
  ssl:
    key-store: C:\Users\Temirlan_Danabekov\mykeys.jks
    key-store-password: letmein
    key-password: letmein

taco:
  orders:
    pageSize: 10
  discount:
    codes:
      abcdef: 10